
public class Ex02_Exception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
			System.out.println("main start");
			int num = 100;
			int result = 0;
			
			//개발자 의심되면 ... 문제가 ...
			try {
				for (int i = 0; i< 10 ; i++) {
					result = num / (int)(Math.random() * 10); // 0~9 난수
					System.out.println("result : " + result + " i :" + i);
				}
			}catch (Exception e) {	//Exception e 유지보수가 힘들어요
				
			}finally {
				
			}
			
			/*for (int i = 0; i< 10 ; i++) {
				result = num / (int)(Math.random() * 10); // 0~9 난수
				System.out.println("result : " + result + " i :" + i);
			}
			System.out.println("main end");
				*/
	}

}
